[config]
base_url = "https://api-giellalt.uit.no"

[grammar]
    [grammar.ga]
    name = "Gaeilge"

    [grammar.fo]
    name = "føroyskt"

    [grammar.smj]
    name = "julevsámegiella"

    [grammar.se]
    name = "davvisámegiella"

    [grammar.nb]
    name = "norsk bokmål"

    [grammar.sma]
    name = "Åarjelsaemien gïele"

    [grammar.sms]
    name = "nuõrttsääʹmǩiõll"

    [grammar.smn]
    name = "anarâškielâ"

    [grammar.kl]
    name = "kalaallisut"

[speller]
    [speller.se]
    name = "davvisámegiella"

    [speller.smn]
    name = "anarâškielâ"

    [speller.sma]
    name = "Åarjelsaemien gïele"

    [speller.smj]
    name = "julevsámegiella"

    [speller.sms]
    name = "nuõrttsääʹmǩiõll"

[hyphenation]
    [hyphenation.se]
    name = "davvisámegiella"

[tts]

[tts.se]
name = "davvisámegiella"

[tts.se.voices]
    [tts.se.voices.biret]
    name = "Biret"
    gender = "female"

    [tts.se.voices.mahtte]
    name = "Máhtte"
    gender = "male"

    [tts.se.voices.sunna]
    name = "Sunná"
    gender = "female"

[tts.sma]
name = "Åarjelsaemien gïele"

[tts.sma.voices]
    [tts.sma.voices.aanna]
    name = "Aanna"
    gender = "female"

[tts.smj]
name = "julevsámegiella"

[tts.smj.voices]
    [tts.smj.voices.nihkol]
    name = "Nihkol"
    gender = "male"

    [tts.smj.voices.abmut]
    name = "Ábmut"
    gender = "male"

    [tts.smj.voices.sigga]
    name = "Siggá"
    gender = "female"
