apiVersion: apps/v1
kind: Deployment
metadata:
  name: divvun-worker-static
  labels:
    app: divvun-worker-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: divvun-worker-static
  template:
    metadata:
      labels:
        app: divvun-worker-static
    spec:
      containers:
      - name: divvun-worker-static
        image: ghcr.io/divvun/divvun-worker-static:latest
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi